### ISSUE TITLE
[Question]: Is there a way to icrease the size of the card/font/icon?

### ISSUE THREAD

**Issue by szemod** [junalmeida/homeassistant-minimalistic-area-card#22]
### What happened?

Would be a nice feature to be able to set the height of the card or set the size of the text and icons

### Card Version

1.0.6

### HomeAssistant Version

Home Assistant Core 2022.6.4

**Comment by szemod** [comment]
Okay, 
it's easy to increase card height and icon size but font size is tricky (I was only able to play with spacing...).

card_mod:
  style: |
    ha-card {
      height: 300px;
      font-size: 2cm !important;
      font-family: Helvetica;
      line-height: 50px;
      text-transform: capitalize;
      font-style: italic;
      font-weight: 900 !important;
      letter-spacing: 0.20em !important;
      word-spacing: 3px;
    --mdc-icon-size: 50px;
    }

**Comment by junalmeida** [comment]
@szemod did it work with card-mod? I would only suggest to use "em" instead of centimeter. So, "1.1em" would increase it proportionally to the parent definition. 
You may also check current source code for places where I set it on nested items of the ha-card (eg the sensor row has a smaller font than title). 
You could reach it like :
```
ha-card .box .card-header {
font-size: 1.1em; /* which means 1.1 times the inherited size? */
} 
```  

If you want to keep my proportional sets, you can keep forcing the root font-size
