### ISSUE TITLE
Use solid color as background

### ISSUE THREAD

**Issue by gfandrea** [junalmeida/homeassistant-minimalistic-area-card#4]
**Describe the solution you'd like**
It could be intresting to use a solid color for the card background, maybe using the HEX code

**Comment by junalmeida** [comment]
I will take you suggestion into consideration, thanks :)

**Comment by seraphx2** [comment]
Can it be more than a consideration? I find it weird you assume everyone wants an image as a background.
Image sources are usually a secondary concern, not primary.
They make it very hard to read the text and icons on the card.

**Comment by junalmeida** [comment]
For me, the image is primary because it is meant to be a smaller version of the native area card, which also has image as a primary concern (https://www.home-assistant.io/dashboards/area/). Without an image probably an icon list card would be enough.

If the image you choose is making it hard to read, probably the image is too bright. Currently the card already darkens the image a bit. I am also considering providing an option to control the dark filter percentage.

**Comment by seraphx2** [comment]
I would hardly call an optional item (that when not supplied defaults to a color, so gives you the option to choose) the primary concern of even the built-in card. And to further that point, the top 3 dashboard configurators (lovelace minimalist, Mushroom, and Dwains) all default to themed colors.

**Comment by kauelima** [comment]
I wanted this and as an alternative I'm just using a colored pixel data as the image.

Example:

`type: custom:minimalistic-area-card
title: Room Name


image: >-
  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=


tap_action:
  action: navigate
  navigation_path: room_name
entities:
  - sensor.temp_roome_name
  - light.room_name
`

**Comment by binarypickle** [comment]
Didn't know you could hard code a png like that. Nice. I was using https://singlecolorimage.com/ to just get a url.

**Comment by seraphx2** [comment]
Yeah. I wish I had thought of that. I'm a web developer, but I don't usually put base64 data in an img tag.
And that's all it really is. Anything that allows you to put a URI for an image would also accept this because at the end of the day, it's being inserted into the `src` property of an `img` tag. And that accepts URI's or base64 data to render an image.

@kauelima Thanks for that...haha.
