### ISSUE TITLE
Local Media Path for Image

### ISSUE THREAD

**Issue by cymone-smart** [junalmeida/homeassistant-minimalistic-area-card#43]
### What happened?

Feature Request:  Would it be possible to display images located in the local media path (i.e., /media/local)?

### Card Version

1.1.8

### HomeAssistant Version

2022.12.8

**Comment by junalmeida** [comment]
If you need a non-public image, I recommend uploading it to an actual Area in home assistant (go to https://your-domain/config/areas/dashboard), then instead of `image: url`, add `area: area_name` to your cards. 
I don't think you can easily use files in /media folder. 

See https://www.home-assistant.io/integrations/media_source/

> Files served from media are protected by Home Assistant authentication unlike those served from www.
