### ISSUE TITLE
[Bug]: icon color

### ISSUE THREAD

**Issue by LtPixel** [junalmeida/homeassistant-minimalistic-area-card#50]
### What happened?

Hey @junalmeida

I love this card... using it on all my Home Assistant screens.
There is one small improvement, that would make it perfect for my setup.
It would be great if you could overwrite the on/off colors of the icons (lights, switches, etc).
In the current setup, my lights might be bright white at 50%... and therefore I'm unabe to glance that they are on (or off).

P.

### Card Version

 v1.1.8

### Home Assistant Version

Home Assistant 2023.1.5

### Browser Version

Google Chrome Version 109.0.5414.74

### Relevant javascript log output

```shell
icon_color_on: rgb(0 255 0 / 50%)
icon_color_off: rgb(255 0 0 / 50%)
```

**Comment by junalmeida** [comment]
Hi,
So, this is not something I can do because all entity buttons are rendered by the native Home Assistant buttons. This card just uses it. As an alternative you could either use a background image that contrasts better, or add the shadow. You can also use other customizations cards to customize an entity color (and that will apply across HA, for eg it should also apply on the More-Info dialog)
